name: "Workflow 1: Shell Commands" # Workflow name shown in GitHub Actions tab

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps:
      - name: 1. Initialization
        run: echo "Starting the workflow"
      - name: 2. Show versions
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python